import { useThemedStyles } from "@/src/theme/useTheme";

/**
 * Styles statiques de l'écran CntsDashboardScreen.
 */
export function useDashboardStyles() {
  return useThemedStyles((c) => ({
    container: { flex: 1, backgroundColor: c.bg },
    scrollContent: { paddingHorizontal: 20 },
    header: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "flex-start",
      paddingTop: 8,
      paddingBottom: 22,
    },
    greeting: {
      color: c.textMuted,
      fontSize: 12,
      fontWeight: "500",
      marginBottom: 3,
    },
    headerTitle: {
      color: c.white,
      fontSize: 24,
      fontWeight: "900",
      letterSpacing: -0.5,
    },
    notifBtn: {
      width: 40,
      height: 40,
      borderRadius: 12,
      backgroundColor: c.cardBg,
      borderWidth: 0.5,
      borderColor: c.cardBorder,
      alignItems: "center",
      justifyContent: "center",
    },
    statsGrid: { flexDirection: "row", gap: 6, marginBottom: 24 },
    sectionHead: {
      flexDirection: "row",
      alignItems: "center",
      gap: 7,
      marginBottom: 10,
      marginTop: 4,
    },
    sectionLabel: {
      color: c.textSubtle,
      fontSize: 10,
      fontWeight: "700",
      letterSpacing: 1.5,
    },
    card: {
      backgroundColor: c.cardBg,
      borderRadius: 16,
      borderWidth: 0.5,
      borderColor: c.cardBorder,
      overflow: "hidden",
      marginBottom: 22,
    },
    empty: { alignItems: "center", padding: 24, gap: 8 },
    emptyText: { color: c.textMuted, fontSize: 13 },
    requestRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 12,
      padding: 13,
      borderBottomWidth: 0.5,
      borderBottomColor: c.cardBorder,
    },
    requestBadge: {
      width: 42,
      height: 42,
      borderRadius: 12,
      alignItems: "center",
      justifyContent: "center",
      flexShrink: 0,
      backgroundColor: c.red + "12",
      borderWidth: 0.5,
      borderColor: c.red + "40",
    },
    requestBadgeText: { color: c.white, fontSize: 13, fontWeight: "900" },
    requestInfo: { flex: 1, gap: 3 },
    requestHospital: { color: c.white, fontSize: 13, fontWeight: "700" },
    requestMeta: { color: c.textMuted, fontSize: 11 },
    vitalPill: {
      flexDirection: "row",
      alignItems: "center",
      gap: 3,
      backgroundColor: c.red + "12",
      borderWidth: 0.5,
      borderColor: c.red + "30",
      paddingHorizontal: 6,
      paddingVertical: 2,
      borderRadius: 6,
    },
    vitalText: {
      color: c.red,
      fontSize: 9,
      fontWeight: "800",
      letterSpacing: 0.5,
    },
    fabWrap: { position: "absolute", right: 22 },
    fab: {
      width: 58,
      height: 58,
      borderRadius: 18,
      backgroundColor: c.red,
      alignItems: "center",
      justifyContent: "center",
      shadowColor: c.red,
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.3,
      shadowRadius: 16,
      elevation: 12,
    },
  }));
}