import { useThemedStyles } from "@/src/theme/useTheme";

export function useLoginStyles() {
  const styles = useThemedStyles((c) => ({
    container: { flex: 1, backgroundColor: c.bg },
    safeArea: { flex: 1, paddingHorizontal: 24 },
    haloBottomLeft: {
      position: "absolute",
      bottom: -60,
      left: -60,
      width: 220,
      height: 220,
      borderRadius: 110,
      backgroundColor: c.redGlow,
    },
    haloTopRight: {
      position: "absolute",
      top: -40,
      right: -40,
      width: 160,
      height: 160,
      borderRadius: 80,
      backgroundColor: c.haloLight,
    },
    backBtn: {
      width: 40,
      height: 40,
      borderRadius: 12,
      backgroundColor: c.cardBg,
      borderWidth: 1,
      borderColor: c.cardBorder,
      alignItems: "center",
      justifyContent: "center",
      marginTop: 8,
      marginBottom: 32,
    },
    body: { flex: 1 },
    headerBlock: { marginBottom: 32, gap: 20 },
    proBadgeRow: { flexDirection: "row", alignItems: "center", gap: 12 },
    proIconWrap: {
      width: 44,
      height: 44,
      backgroundColor: c.red,
      borderRadius: 12,
      alignItems: "center",
      justifyContent: "center",
    },
    proBadgeText: { gap: 2 },
    proEyebrow: {
      color: c.textSubtle,
      fontSize: 9,
      fontWeight: "600",
      letterSpacing: 2,
    },
    proTitle: { color: c.white, fontSize: 16, fontWeight: "700" },
    titleBlock: { gap: 6 },
    title: {
      color: c.white,
      fontSize: 28,
      fontWeight: "800",
      letterSpacing: -0.5,
    },
    subtitle: { color: c.textMuted, fontSize: 14, lineHeight: 21 },
    formBlock: { marginBottom: 8 },
    forgotRow: {
      alignSelf: "flex-end",
      paddingVertical: 4,
      marginTop: -4,
      marginBottom: 8,
    },
    forgotText: { color: c.red, fontSize: 13, fontWeight: "600" },
    ctaBtn: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      gap: 10,
      backgroundColor: c.red,
      borderRadius: 16,
      paddingVertical: 17,
      marginBottom: 24,
    },
    ctaBtnDisabled: { opacity: 0.5 },
    ctaBtnText: {
      color: c.white,
      fontSize: 16,
      fontWeight: "700",
      letterSpacing: 0.2,
    },
    ctaBtnIcon: {
      width: 28,
      height: 28,
      borderRadius: 8,
      backgroundColor: "rgba(255,255,255,0.18)",
      alignItems: "center",
      justifyContent: "center",
    },
    securityRow: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      gap: 6,
      paddingBottom: 10,
    },
    securityText: { color: c.textSubtle, fontSize: 11, letterSpacing: 0.3 },
  }));

  return { styles };
}
