import { useThemedStyles } from "@/src/theme/useTheme";

export function usePendingReviewStyles() {
  const styles = useThemedStyles((c) => ({
    container: { flex: 1, backgroundColor: c.bg },
    safeArea: { flex: 1, paddingHorizontal: 24 },
    haloCenter: {
      position: "absolute",
      top: -60,
      left: "50%",
      marginLeft: -110,
      width: 220,
      height: 220,
      borderRadius: 110,
      backgroundColor: "rgba(250,199,117,0.08)",
    },
    body: {
      paddingVertical: 24,
      alignItems: "center",
      justifyContent: "center",
      gap: 28,
    },
    // ── Icône ──
    iconBlock: {
      position: "relative",
      alignItems: "center",
      justifyContent: "center",
    },
    iconRing2: {
      width: 120,
      height: 120,
      borderRadius: 60,
      backgroundColor: "rgba(250,199,117,0.06)",
      borderWidth: 1,
      borderColor: "rgba(250,199,117,0.12)",
      alignItems: "center",
      justifyContent: "center",
    },
    iconRing1: {
      width: 90,
      height: 90,
      borderRadius: 45,
      backgroundColor: "rgba(250,199,117,0.10)",
      borderWidth: 1,
      borderColor: "rgba(250,199,117,0.20)",
      alignItems: "center",
      justifyContent: "center",
    },
    iconCenter: {
      width: 64,
      height: 64,
      borderRadius: 20,
      backgroundColor: "rgba(250,199,117,0.15)",
      alignItems: "center",
      justifyContent: "center",
    },
    iconBadge: {
      position: "absolute",
      bottom: 4,
      right: 4,
      width: 22,
      height: 22,
      borderRadius: 11,
      backgroundColor: c.success,
      alignItems: "center",
      justifyContent: "center",
      borderWidth: 2,
      borderColor: c.bg,
    },
    // ── Texte ──
    textBlock: { alignItems: "center", gap: 10 },
    eyebrow: {
      color: c.textSubtle,
      fontSize: 10,
      fontWeight: "600",
      letterSpacing: 2.5,
    },
    title: {
      color: c.white,
      fontSize: 30,
      fontWeight: "800",
      textAlign: "center",
      letterSpacing: -0.5,
      lineHeight: 38,
    },
    subtitle: {
      color: c.textMuted,
      fontSize: 14,
      textAlign: "center",
      lineHeight: 22,
      maxWidth: 300,
    },
    // ── Timeline ──
    timelineCard: {
      backgroundColor: c.cardBg,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: c.cardBorder,
      padding: 16,
      alignSelf: "stretch",
    },
    timelineRow: { flexDirection: "row", alignItems: "center", gap: 12 },
    timelineIconWrap: {
      width: 32,
      height: 32,
      borderRadius: 9,
      borderWidth: 1,
      alignItems: "center",
      justifyContent: "center",
    },
    timelineLabel: {
      flex: 1,
      color: c.textMuted,
      fontSize: 13,
      fontWeight: "500",
    },
    timelineLabelDone: { color: c.success, fontWeight: "600" },
    timelineLabelActive: { color: c.amber, fontWeight: "600" },
    timelineConnector: {
      width: 1,
      height: 14,
      backgroundColor: c.cardBorder,
      marginLeft: 15,
      marginVertical: 4,
    },
    pendingDot: {
      backgroundColor: "rgba(250,199,117,0.15)",
      borderRadius: 6,
      paddingHorizontal: 7,
      paddingVertical: 2,
      borderWidth: 1,
      borderColor: "rgba(250,199,117,0.25)",
    },
    pendingDotText: { color: c.amber, fontSize: 10, fontWeight: "700" },
    // ── Email card ──
    emailCard: {
      flexDirection: "row",
      alignItems: "flex-start",
      gap: 10,
      backgroundColor: "rgba(34,197,94,0.07)",
      borderRadius: 12,
      borderWidth: 1,
      borderColor: "rgba(34,197,94,0.16)",
      padding: 12,
      alignSelf: "stretch",
    },
    emailCardText: {
      flex: 1,
      color: "rgba(34,197,94,0.70)",
      fontSize: 12,
      lineHeight: 18,
    },
    // ── Footer ──
    footer: { paddingBottom: 10, gap: 12 },
    ctaBtn: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      gap: 10,
      backgroundColor: c.red,
      borderRadius: 16,
      paddingVertical: 17,
    },
    ctaBtnText: { color: c.white, fontSize: 16, fontWeight: "700" },
    ctaBtnIcon: {
      width: 28,
      height: 28,
      borderRadius: 8,
      backgroundColor: "rgba(255,255,255,0.18)",
      alignItems: "center",
      justifyContent: "center",
    },
    secondaryBtn: { alignItems: "center", paddingVertical: 12 },
    secondaryBtnText: { color: c.textMuted, fontSize: 14, fontWeight: "500" },
  }));

  return { styles };
}
